language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite

before_script:
  - printf "[sqlite3]\nsqlite3.extension_dir = /usr/lib\n" > php.sqlite.ini
  - bash -c 'if [[ $TRAVIS_PHP_VERSION != hhvm* ]]; then phpenv config-add php.sqlite.ini; fi;'
  - composer install

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/coveralls -v

matrix:
  exclude:
    - env: DB=mysql # travis does not support MySQL 5.6 yet
    - php: hhvm
      env: DB=pgsql # driver currently unsupported by HHVM
    - php: hhvm-nightly
      env: DB=pgsql # driver currently unsupported by HHVM
  allow_failures:
    - php: hhvm-nightly
