language: php

php:
  - 5.5
  - 5.6
  - hhvm

env:
  - DB=mysql
  - DB=pgsql

before_script:
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -U postgres -c 'create extension postgis'; fi"
  - composer install

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.$DB.xml --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/coveralls -v
