language: php

php:
  - 5.6
  - 7
  - hhvm

env:
  - ENGINE=PDO_MYSQL56
  - ENGINE=PDO_MYSQL57
  - ENGINE=PDO_MYSQL_MARIADB55
  - ENGINE=PDO_MYSQL_MARIADB10
  - ENGINE=PDO_PGSQL
  - ENGINE=SQLite3
  - ENGINE=GEOS

before_script:
  - if [[ $ENGINE = PDO_MYSQL56 ]]; then ENGINE=PDO_MYSQL; sudo bash travis/install-mysql-5.6.sh; fi;
  - if [[ $ENGINE = PDO_MYSQL57 ]]; then ENGINE=PDO_MYSQL; sudo bash travis/install-mysql-5.7.sh; fi;
  - if [[ $ENGINE = PDO_MYSQL_MARIADB55 ]]; then ENGINE=PDO_MYSQL; sudo VERSION=5.5 bash travis/install-mariadb.sh; fi;
  - if [[ $ENGINE = PDO_MYSQL_MARIADB10 ]]; then ENGINE=PDO_MYSQL; sudo VERSION=10.0 bash travis/install-mariadb.sh; fi;
  - if [[ $ENGINE = GEOS ]]; then bash travis/install-geos.sh; fi;
  - if [[ $ENGINE = SQLite3 ]]; then bash travis/install-spatialite.sh; fi;
  - composer self-update
  - composer install

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/coveralls -v

matrix:
  exclude:
    - php: 7
      env: ENGINE=GEOS # no bindings for PHP 7 yet
    - php: hhvm
      env: ENGINE=PDO_PGSQL # driver currently unsupported by HHVM
    - php: hhvm
      env: ENGINE=GEOS # extension currently unsupported by HHVM
    - php: hhvm
      env: ENGINE=PDO_MYSQL57 # current installation script uninstalls HHVM
    - php: hhvm
      env: ENGINE=PDO_MYSQL_MARIADB55 # current installation script uninstalls HHVM
    - php: hhvm
      env: ENGINE=PDO_MYSQL_MARIADB10 # current installation script uninstalls HHVM
  allow_failures:
    - php: hhvm
